### ISSUE TITLE
mmin and mmax are not correctly passed by inverse_imf

### ISSUE THREAD

**Issue by smeingast** [keflavich/imf#13] opened 2019-08-12 12:52 UTC
Hey there. When I call inverse_imf with the arguments `mmin` or `mmax`, the created mass function instance does not use these values. For instance

`inverse_imf(np.random.random(10000000), massfunc="kroupa", mmin=0.01, mmax=200.0)`

still returns a minimum mass of 0.03 and a maximum of 120. ;)

**Comment by keflavich** [comment] 2019-08-12 12:55
uh oh.... that looks like a bug.  
![image](https://user-images.githubusercontent.com/143715/62866438-09526800-bd11-11e9-9e70-2404f9398b72.png) is correct.

This should be easy to fix; we just need to pass those parameters onto the `massfunc` correctly.

In the meantime, you can probably work around w/`inverse_imf(..., massfunc=imf.Kroupa(mmin=0.01, mmax=200.0))`

**Comment by smeingast** [comment] 2019-08-12 13:09
Indeed and thanks for the quick response. 🙂 I already have a workaround going here locally, but I will update my repo once you implemented the fix. Thanks!!

**Comment by keflavich** [comment] 2019-11-14 22:22
eb479c5 may have solved this: I now use `rvs` directly in `inverse_imf`

**Comment by wbuthod** [comment] 2020-05-06 21:03
I'm having a similar issue. For example:

    import imf, random
    nmin,nmax = 201.0, 0.0
    while True:
        m = imf.inverse_imf([random.random()],massfunc=imf.Kroupa(mmin=0.01,mmax=200))[0]
        if m < nmin:
            nmin=m
            print(nmin,nmax)
        if m > nmax:
            nmax=m
            print(nmin,nmax)

After some run time, the results still converge at 0.03 and 120.0

**Comment by keflavich** [comment] 2020-05-06 21:20
A much simpler test is `imf.inverse_imf(1,massfunc=imf.Kroupa(mmin=0.01,mmax=200))`

In this case, the problem is that `inverse_imf` is overriding the `mmin`/`mmax`.  Instead, try:
`imf.inverse_imf(1,massfunc=imf.Kroupa(), mmin=0.01,mmax=200)`
i.e., pass `mmin`/`mmax` to `inverse_imf` instead of to `imf.Kroupa`.

This is not great UI design; I'll see if there's a simple fix...

**Comment by wbuthod** [comment] 2020-05-06 21:25
That appears to work for mmax, but not mmin:

    >>> imf.inverse_imf([0,1],massfunc=imf.Kroupa(),mmin=0.01,mmax=200)
    array([2.99050745e-02, 1.99013557e+02])
    >>> imf.inverse_imf([0,1],massfunc=imf.Kroupa(),mmin=0.01,mmax=60)
    array([2.99163452e-02, 5.97398875e+01])

**Comment by keflavich** [comment] 2020-05-06 21:41
uh, hmm.  It should.  This might be a deeper problem.  I did just push a commit fixing the UI though

**Comment by keflavich** [comment] 2020-05-06 21:57
I'm actively debugging this, but I'm introducing some bugs along the way... =(

**Comment by wbuthod** [comment] 2020-05-07 18:34
works for me now.

    >>> import imf
    >>> print(imf.inverse_imf([0,1],mmin=0.01,mmax=120))
    [1.0047232e-02 1.1943852e+02]
    >>> print(imf.inverse_imf([0,1],mmin=0.02,mmax=10))
    [0.0200624 9.9689924]
    >>>>

**Comment by keflavich** [comment] 2020-05-07 18:46
Great, closing!  Raise a new issue if this comes back up

**Closed by keflavich** 2020-05-07 18:46 UTC
